### PR TITLE
Updated: Provide Service Account as JSON for Google Speech

### PR DESCRIPTION
**Pull request by ardian4**
added: Use JSON key for service account for Speech plugins

Jira Ticket: https://issues.cask.co/browse/PLUGIN-170

### CODE REVIEW

**Review by rmstar — COMMENTED** [review]
Avoid code duplication by extending GCPConfig instead of PluginConfig, as you have done in other plugins.

**Comment by ardian4** [comment]
> Avoid code duplication by extending GCPConfig instead of PluginConfig, as you have done in other plugins.

@rmstar 
The reason why it was extended from PluginConfig and not from GCPConfig is that GCPConfig has the property ``project``, which is not needed for this plugin.
 How we should proceed?  
 One option is to create the widget and hide it.
image

**Comment by rmstar** [comment]
> One option is to create the widget and hide it.

@ardian4 yes, this might be a better option. I'd prefer to avoid code duplication.

**Comment by ardian4** [comment]
> > One option is to create the widget and hide it.
> 
> @ardian4 yes, this might be a better option. I'd prefer to avoid code duplication.

@rmstar DONE

**Review by rmstar — APPROVED** [review]
Please squash commits

**Comment by ardian4** [comment]
> Please squash commits

Done

**Pull request merged**
