### PR TITLE
PLUGIN-221: BigQuerySink validation for case insensitive fields

### PR DESCRIPTION
**Pull request by flakrimjusufi**
PIpeline Studio - BigQuery sink validation doesn't check the schema
JIRA Ticket: https://cdap.atlassian.net/browse/PLUGIN-221

### CODE REVIEW

**Comment by nbesimi** [comment]
It seems OK to me.

**Review by rmstar — COMMENTED** [review]
The JIRA also talks about another issue:
```
The field name had a character not  not accepted by BigQuery ("-").
```
Can you please update this PR this address this. Thanks!

**Comment by flakrimjusufi** [comment]
> The JIRA also talks about another issue:
> 
> ```
> The field name had a character not  not accepted by BigQuery ("-").
> ```
> 
> Can you please update this PR this address this. Thanks!

This case is already handled in this section of code: 

https://github.com/data-integrations/google-cloud/blob/0301b9d5f75adb3f9745e6a35d0e3ee52652847c/src/main/java/io/cdap/plugin/gcp/bigquery/sink/BigQuerySinkConfig.java#L314-L319

**Review by rmstar — APPROVED** [review]
👍 
Please squash commits

**Comment by flakrimjusufi** [comment]
> Please squash commits

Commits squashed.

**Pull request merged**
