### PR TITLE
PLUGIN-1090: spanner timeout issue on new DB

### PR DESCRIPTION
**Pull request by sumitnigamcs**
spanner timeout issue on new DB

### CODE REVIEW

**Comment by sumitnigamcs** [comment]
@itsankit-google @rmstar Please review

**Review by itsankit-google — APPROVED** [review]
LGTM. Please test and verify the changes before merge.

**Comment by sumitnigamcs** [comment]
> LGTM. Please test and verify the changes before merge.

@itsankit-google Tested, and manual test document attached on jira by @sahilkapoor301992 
Automation execution result will be confirmed by @sawantpritam

**Comment by itsankit-google** [comment]
> > LGTM. Please test and verify the changes before merge.
> 
> @itsankit-google Tested, and document attached on jira by @sahilkapoor301992

@sumitnigamcs Testing with e2e tests enabled is not yet done with these changes. Please check with @sawantpritam.

**Comment by ksahilCF** [comment]
> > > LGTM. Please test and verify the changes before merge.
> > 
> > 
> > @itsankit-google Tested, and document attached on jira by @sahilkapoor301992
> 
> @sumitnigamcs Testing with e2e tests enabled is not yet done with these changes. Please check with @sawantpritam.

@itsankit-google tested with e2e tests and it is working as expected.

**Comment by itsankit-google** [comment]
> > > > LGTM. Please test and verify the changes before merge.
> > > 
> > > 
> > > @itsankit-google Tested, and document attached on jira by @sahilkapoor301992
> > 
> > 
> > @sumitnigamcs Testing with e2e tests enabled is not yet done with these changes. Please check with @sawantpritam.
> 
> @itsankit-google tested with e2e tests and it is working as expected.

Thanks @ksahilCF for the update, please ensure it is cherry-picked to `release/0.20` for 6.7.

**Pull request merged**
