### PR TITLE
Run only required tests on push

### PR DESCRIPTION
**Pull request by sawantpritam**
@itsankit-google @rmstar Please review.

This PR depends on https://github.com/cdapio/cdap-e2e-tests/pull/102

Added Required runner for only BigQuery. Once this PR is approved. I will add for other plugins as well.

### CODE REVIEW

**Review by itsankit-google — CHANGES_REQUESTED** [review]
Can we keep one tag named as `REQUIRED` and one common runner?
Do we really need to maintain different required runners for all plugins?

**Comment by sawantpritam** [comment]
> Can we keep one tag named as `REQUIRED` and one common runner? Do we really need to maintain different required runners for all plugins?

If we maintain single required runner then those required tests will get executed in sequence. Currently with different required runners 2 runners get executed in parallel.

**Review by itsankit-google — APPROVED** [review]

**Comment by itsankit-google** [comment]
Please squash commits

**Comment by sawantpritam** [comment]
> Please squash commits

Commits squashed.

**Review by itsankit-google — APPROVED** [review]
Please squash commits.

**Comment by sawantpritam** [comment]
> Commits squashed.

Commits squashed.

**Pull request merged**
