### PR TITLE
Cherry pick for PLUGIN-170-spanner agains release/0.14 

### PR DESCRIPTION
**Pull request by ardian4**
Release 0.14 cherry pick of https://github.com/data-integrations/google-cloud/pull/368
Jira Ticket https://issues.cask.co/browse/PLUGIN-170

### CODE REVIEW

**Comment by rmstar** [comment]
@ardian4 please resolve conflict.

**Comment by ardian4** [comment]
> @ardian4 please resolve conflict.

done

**Review by rmstar — APPROVED** [review]
please squash commits

**Comment by ardian4** [comment]
> please squash commits

squashed

**Pull request merged**
