### PR TITLE
Release 0.15 Cherry Pick PLUGIN-170 - Spanner

### PR DESCRIPTION
**Pull request by ardian4**
Release 0.15 cherry pick of https://github.com/data-integrations/google-cloud/pull/368
Jira Ticket https://issues.cask.co/browse/PLUGIN-170

### CODE REVIEW

**Comment by rmstar** [comment]
@ardian4 please resolve conflict.

**Comment by ardian4** [comment]
> @ardian4 please resolve conflict.

Done

**Review by rmstar — APPROVED** [review]
Please squash commits

**Comment by ardian4** [comment]
squashed

**Pull request merged**
