### PR TITLE
CDAP-14355 Verify referenceName during deployment

### PR DESCRIPTION
**Pull request by rohitsinha54**
- Add validation for referenceName during deployment

### CODE REVIEW

**Comment by albertshau** [comment]
I merged my PR, can you rebase this against release

**Comment by rohitsinha54** [comment]
@albertshau : Done. Please have a look.

**Review by albertshau — COMMENTED** [review]
I think it's better to add a validate method to GCPReferenceSourceConfig and GCPReferenceSinkConfig and make sure their children all call super.validate() in their validate methods.

For example, the GCS plugins are missing validation now because they don't actually extend AbstractFileSourceConfig

**Review by albertshau — APPROVED** [review]
lgtm

**Pull request merged**
