### PR TITLE
Merge release 0 11 0

### PR DESCRIPTION
**Pull request by albertshau**

### CODE REVIEW

**Comment by anwar6953** [comment]
Were there conflicts?
If not, couldn't we merge directly from the release branch, without the intermediary `merge-release-0-11-0` branch?

**Comment by albertshau** [comment]
pom conflicts with the versions

**Comment by anwar6953** [comment]
Ok.
I'll let @rohitsinha54 or @CuriousVini give an approval, since most of the changes are theirs.

**Review by CuriousVini — APPROVED** [review]
lgtm

**Review by rohitsinha54 — APPROVED** [review]

**Pull request merged**
