### PR TITLE
Added Provide Service Account as JSON for Plugins: GCS Move, GCS Copy, GCS Sink, GCS MultiSink

### PR DESCRIPTION
**Pull request by ardian4**
Updated: Provide Service Account as JSON for GCS Move, GCS Copy, GCS Sink, GCS MultiSink plugins

Jira Ticket: https://issues.cask.co/browse/PLUGIN-170

### CODE REVIEW

**Review by rmstar — COMMENTED** [review]
Let's keep the validation logic and error messages consistent across all the google-cloud plugins. Please make the same changes requested in #357

**Review by rmstar — APPROVED** [review]
Please squash your commits

**Comment by ardian4** [comment]
@rmstar squashed

**Comment by ardian4** [comment]
> Please squash your commits

Done

**Pull request merged**
